<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "boku_no_theme"
 *
 * Auto generated by Extension Builder 2021-08-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'FormCollection',
    'description' => 'TYPO3 Forms collection for simple default forms',
    'category' => 'plugin',
    'author' => 'Ing. Markus Ketterer',
    'author_email' => '4tmestorage@gmail.com',
    'state' => 'alpha',
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '12.4.0-12.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
